name: CI/CD WORKFLOW
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      # Debug: Udskriv miljøvariabler for at sikre, at de er sat korrekt
      - name: Debug Environment Variables
        run: env | grep DB_ || echo "No DB_ variables found!"

      # Debug: Test databaseforbindelse til Neon.tech
      - name: Test Database Connection
        run: nc -zv ${{ secrets.DB_HOST }} ${{ secrets.DB_PORT }}

      - name: Build with Maven (Debug)
        run: mvn --batch-mode clean package -X
        env:
          DEPLOYED: ${{ secrets.DEPLOYED }}
          ISSUER: ${{ secrets.ISSUER }}
          TOKEN_EXPIRE_TIME: ${{ secrets.TOKEN_EXPIRE_TIME }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USE_SSL: ${{ secrets.DB_USE_SSL }}

      # Debug: Hvis Maven-tests fejler, udskriv Surefire logs
      - name: Show Surefire Test Logs (If Tests Fail)
        if: failure()
        run: cat target/surefire-reports/*.txt || true

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hotel_api:latest
