name: CI/CD WORKFLOW
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      # Debug: Udskriv miljøvariabler for at sikre, at de er sat korrekt
      - name: Debug Environment Variables
        run: |
          echo "DB_HOST=${{ secrets.DB_HOST }}"
          echo "DB_PORT=${{ secrets.DB_PORT }}"
          echo "DB_USERNAME=${{ secrets.DB_USERNAME }}"
          echo "DB_PASSWORD=********"  # Skjuler password, så det ikke vises i logs

      - name: Test Database Connection
        run: |
          if [ -z "${{ secrets.DB_HOST }}" ] || [ -z "${{ secrets.DB_PORT }}" ] || [ -z "${{ secrets.DB_USERNAME }}" ] || [ -z "${{ secrets.DB_PASSWORD }}" ]; then
            echo "⚠️ En af database-secrets er ikke sat korrekt!"
            exit 1
          fi
          nc -zv ${{ secrets.DB_HOST }} ${{ secrets.DB_PORT }}

          echo "Databaseforbindelse ser ud til at virke!"
      

      - name: Build with Maven (Debug)
        run: mvn --batch-mode clean package
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEPLOYED: ${{ secrets.DEPLOYED }}
          ISSUER: ${{ secrets.ISSUER }}
          TOKEN_EXPIRE_TIME: ${{ secrets.TOKEN_EXPIRE_TIME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_USE_SSL: ${{ secrets.DB_USE_SSL }}



      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/hotel_api:latest
